on:
  schedule: [{cron: "*/7 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  status:
    runs-on: ubuntu-latest
    name: Update Discord Status
    steps:
      - name: Checkout files
        uses: actions/checkout@v3
      - name: Update Status
        uses: CompeyDev/discord-status-action@0.3.2
        with:
          file: index.html
          id: "851086728634957855" # Replace with your Discord User ID.
      - name: Commit and push if there are changes
        run: |-
          git diff
          git config --global user.email "hi@devcomp.xyz" # Replace with an email associated to your GitHub Account.
          git config --global user.name "StatsBot"
          git diff --quiet || (git add -u && git commit -m "🚀 Update Discord Status")
          git push               
